object Versions {
    const val coreKtx = "1.12.0"
    const val appCompat = "1.6.1"
    const val materialDesign = "1.10.0"
    const val constraintLayout = "2.1.4"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val esspresso = "3.5.1"
    const val daggerHilt = "2.46.1"
    const val hiltCompiler = "1.1.0"
    const val navigationKtx = "2.5.3"
    const val retrofit = "2.9.0"
    const val loggingInterceptor = "5.0.0-alpha.6"
    const val lifecycle = "2.6.2"
    const val location = "21.0.1"
    const val splashApi = "1.0.0"
    const val maps = "18.2.0"
    const val prefs = "1.10.0"
}